### ISSUE TITLE
Ruby 2 is EOL but not reported

### ISSUE THREAD

**Issue by yansifw** [xeol-io/xeol#94]
**What happened**:
Running xeol on ruby 2 docker image does not report Ruby EOL

![image](https://github.com/xeol-io/xeol/assets/107258831/2ebbd0ad-ec16-4c97-9c93-a1bc7889f225)

**What you expected to happen**:
Ruby 2 EOL should appear

**How to reproduce it (as minimally and precisely as possible)**:
xeol ruby:2 --scope all-layers

**Anything else we need to know?**:

**Environment**:
- Output of `xeol version`:
Application:          xeol
Version:              0.4.9
Syft Version:         v0.83.1
GitCommit:            104207656f8e189bb7409d1e723987839381e231
Platform:             darwin/arm64
GoVersion:            go1.18.10
Compiler:             gc
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by noqcks** [comment]
Thanks for reporting this. It looks as though syft correctly detects this, so no problem there.

```
$ syft ruby:2
 ✔ Pulled image
 ✔ Loaded image
 ✔ Parsed image
 ✔ Cataloged packages      [466 packages]

NAME                          VERSION                         TYPE
ruby                          2.7.8p225                       binary
```

However, I believe the version string it gives us `2.7.8p225` is the problem, since we have to match it to a release cycle version from https://endoflife.date/ruby 

We'll need to add some parsing to normalize this version string.
